main:
  apikey:
  apisecret:

logging:
  version: 1

  formatters:
    simple:
      format: "%(asctime)s [%(levelname)-5.5s][%(name)s] %(msg)s"

  handlers:
    console:
      formatter: simple
      class: logging.StreamHandler

  root:
    level: DEBUG
    handlers:
      - console
